/**
 * CORPUS — conversa completa com o agente do Gemini sobre arbitragem, freebets e
 * apostas de promoção (exportada em 30/07/2026 do PDF "blank.pdf" enviado pelo
 * usuário; o original ficou em docs/conhecimento/).
 *
 * Por que .ts e não .md/.json: o `tsc` não copia arquivos não-TS para dist/, então
 * um import de .md/.json quebraria em produção (mesma razão de IA/regrasCasas.ts).
 *
 * Uso: a skill `buscar_conhecimento` do Agente faz busca por palavra-chave nestes
 * trechos (ver IA/conhecimento/index.ts). A DOUTRINA destilada — as regras que o
 * agente deve seguir sempre — está em conhecimento/doutrinaPromocoes.ts; este
 * corpus é a fonte bruta, para quando o usuário perguntar "o que combinamos sobre
 * X" ou pedir o raciocínio original com os números daquele dia.
 */

export interface TrechoConversa {
  /** Índice na conversa (1 = primeira troca). */
  n: number;
  pergunta: string;
  resposta: string;
}

export const CONVERSA_GEMINI_PROMOCOES: TrechoConversa[] = [
  {
    n: 1,
    pergunta: "primeira feita",
    resposta: "Show de bola! Primeira perna 100% blindada e protegida.\n\nAgora é só relaxar e acompanhar os primeiros 45 minutos de Internacional x Flamengo.\n\nPor volta das 20:15–20:20 (final do 1º tempo), o cenário se define:\n\n • 0 ou 1 gol no 1º Tempo: A aposta bate na Superbet, você recupera R$ 56,48 no saldo\n real, a missão é cumprida na Joga Junto e a Freebet de R$ 10 é garantida (lucro final de\n ~R$ 4,50 no bolso e operação encerrada).\n\n • 2 ou mais gols no 1º Tempo: A perna 1 dá GREEN na Joga Junto! A múltipla ganha\n força e passamos a monitorar o jogo do Mirassol (que termina perto das 21:20).\n\nMe avise aqui assim que terminar o 1º tempo em Porto Alegre!",
  },
  {
    n: 2,
    pergunta: "Foi menos 1.5 de gols no 1 tempo no jogo do flamengo",
    resposta: "Excelente! Cobertura executada com sucesso e risco zero.\n\nA aposta bateu exatamente na Superbet, garantindo a proteção da sua banca. Veja como ficou\no saldo da operação:\n\n • Superbet (Cobertura): Ganhou R$ 56,48 (retornou seus R$ 39,50 + R$ 16,98 de lucro).\n\n • Joga Junto (Múltipla): Múltipla encerrada (-R$ 20,00).\n\n • Saldo Atual em Dinheiro Real: Perda temporária controlada de apenas -R$ 3,02.\n\n O Bônus Garantido\n\nComo a múltipla de R$ 20,00 na Joga Junto foi concluída e liquidada, você cumpriu a missão\ncom sucesso. A Joga Junto agora te entrega a Freebet de R$ 10,00.\n\nQuando convertemos essa Freebet de R$ 10 em dinheiro real (extraindo em torno de R$ 7,50 a\nR$ 8,00 em uma aposta simples coberta), você cobre essa diferença de R$ 3,02 e finaliza a\noperação com +R$ 4,50 a +R$ 5,00 de lucro líquido limpo.\n\nDê uma olhada no painel de bônus da Joga Junto para ver se a Freebet de R$ 10 já consta\npor lá ou se ainda está aguardando a liquidação total das outras partidas.\n\nAssim que ela estiver disponível no seu saldo, me avise! Quer converter essa de R$ 10 logo ou\njá partimos para organizar a Freebet de R$ 100 da Novibet?",
  },
  {
    n: 3,
    pergunta: "E uma boa notícia ainda recebi um cashback de 50% voltou 10 reais",
    resposta: "Notícia espetacular! Isso é o que chamamos de forra dupla!\n\nCom esses R$ 10,00 de cashback que voltaram para a sua conta, a matemática da operação\nficou ainda mais lucrativa.\n\nOlha como os seus números foram recalculados para cima:\n\n Nova Matemática Atualizada\n\n 1. Gasto na Joga Junto: R$ 20,00 - R$ 10,00 (Cashback) = Perda real de apenas R$\n 10,00.\n\n 2. Retorno na Superbet (Cobertura): R$ 56,48 (Retornou seus R$ 39,50 de aposta + R$\n 16,98 de lucro da cobertura).\n\n 3. Resultado Parcial (Dinheiro Real na Mão):\n\n ◦ R$56, 48 − R$10, 00(JogaJunto) − R$39, 50(Superbet) =\n +R$6, 98 DE LUCRO DIRETO!\nOu seja: Você já lucrou quase R$ 7,00 reais direto no dinheiro real ANTES MESMO de\nusar a Freebet!\n\n O Retorno Total da Operação\n\n • Lucro no Qualificador (com Cashback): +R$ 6,98\n\n • Conversão da Freebet de R$ 10: ~+R$ 7,50\n\n • Lucro Líquido Final Total: ~R$ 14,50 a R$ 15,00 no bolso!\n\nSua banca acabou de crescer sem risco nenhum, exatamente como planejado.\n\n Qual o próximo passo?\n\n 1. Queremos extrair logo essa Freebet de R$ 10 da Joga Junto (se ela já caiu no seu\n saldo)?\n\n 2. Ou prefere ir preparando a artilharia pesada para a Freebet de R$ 100 da Novibet?",
  },
  {
    n: 4,
    pergunta: "E recebi a Freebet na joga junto e já vamos preparar essa free Bet para o\npróximo jogo",
    resposta: "Boa! Nada melhor do que operar com a banca da casa. Vamos deixar essa Freebet\nengatilhada para extrair o maior valor possível do próximo jogo.\n\nPara garantir que a gente não rasgue esse bônus, vale passar por um checklist rápido antes de\nmontar o bilhete:\n\n • Cheque as regras da casa: Dê uma olhada rápida na odd mínima exigida pela Joga\n Junto para a validação da Freebet (geralmente gira entre 1.80 e 2.00) e na data de\n expiração. Lembre-se também de que apostas com Freebet costumam retornar apenas o\n lucro líquido (o ganho total menos o valor do cupom).\n\n • Defina a estratégia de odd:\n\n ◦ Conservadora / Consistente: Odds entre 1.80 e 2.20 em mercados de boa liquidez\n (como Ambas Marcam ou Over Gols em times ofensivos) para garantir que você\n converta o bônus em saldo real com mais frequência.\n\n ◦ Agressiva (Extrair Máximo Valor): Como o valor apostado não sai do seu bolso,\n apostar em odds mais esticadas (2.80 a 3.50) compensa matematicamente o fato\n de você não receber o valor do cupom de volta, gerando um retorno\n proporcionalmente maior se bater.\n\nQual é o jogo da vez que você está de olho e qual a odd mínima exigida para essa promoção?",
  },
  {
    n: 5,
    pergunta: "Odd mínima 2.00",
    resposta: "Perfeito! Odd mínima de 2.00.\n\nCom essa regra, para tirarmos o máximo proveito dessa Freebet de R$ 10,00, o ideal é\nbuscarmos uma odd na Joga Junto entre 2.00 e 2.30, fazendo a cobertura do lado oposto em\noutra casa (como a Superbet).\n\nQual é o próximo jogo que você tem em vista agora para aplicarmos essa Freebet? Manda o\nnome dos times, o mercado escolhido e a odd lá na Joga Junto que calculo o valor exato da\ncobertura para você!",
  },
  {
    n: 6,
    pergunta: "E se eu pegar uma Odd 4.30 ? O lucro é maior ?",
    resposta: "Sim, o lucro é bem maior! Nas Freebets do tipo SNR (onde o valor da ficha de R$\n10 não volta para você, apenas o lucro líquido), quanto maior a odd, maior é a sua taxa de\nretenção e mais dinheiro real você coloca no bolso.\n\nA diferença prática entre as odds fica assim:\n\n Comparativo de Lucro (Freebet R$ 10)\n\n • Com Odd 2.00:\n\n ◦ Lucro potencial na Freebet: R$ 10,00 (10 × 1.00)\n\n ◦ Lucro líquido garantido na mão: ~R$ 5,00 (retenção de 50%)\n\n • Com Odd 4.30:\n\n ◦ Lucro potencial na Freebet: R$ 33,00 (10 × 3.30)\n\n ◦ Lucro líquido garantido na mão: ~R$ 7,20 a R$ 7,50 (retenção de mais de 72%)\n\n Por que isso acontece?\nComo a casa de apostas \"recolhe\" a ficha de R$ 10,00 quando a Freebet é resolvida, apostar\nem odds baixas faz você perder uma fatia percentual muito grande do bônus. Quando você\nbusca odds na faixa de 4.00 a 4.50, você dilui o peso dessa ficha perdida e maximiza a\nconversão em dinheiro de verdade.\n\n O que muda na cobertura?\n\nComo a Freebet é pequena (R$ 10), buscar uma odd 4.30 vai exigir pouquíssimo saldo na casa\nde cobertura: apenas cerca de R$ 25,00 a R$ 26,00 na Superbet (no mercado oposto, que terá\numa odd bem baixa, em torno de 1.28).\n\nSe você encontrou um jogo na Joga Junto com odd perto de 4.30, manda os dados dele e a\nodd de cobertura que calculo a entrada no centavo para você!",
  },
  {
    n: 7,
    pergunta: "Peguei uma Odd 7,75 para amanhã às 19:30",
    resposta: "Essa odd de 7.75 vai puxar uma taxa de retenção fantástica na Freebet!\n\nEm apostas do tipo SNR (onde a casa não devolve o valor da ficha de R$ 10,00), pegar odds\nmais altas é a melhor estratégia para extrair o máximo de valor do bônus.\n\n O Cenário com Odd 7.75\n\n • Retorno Líquido da Freebet (Joga Junto): R$10, 00 × (7.75 − 1) = R$67, 50 de\n lucro direto se ela bater.\n\n • Aporte Exigido na Cobertura: Por ter uma odd alta no bônus, a odd do lado oposto na\n cobertura vai estar bem baixinha (perto de 1.12 a 1.15). Isso vai exigir entre R$ 58,00 e\n R$ 60,00 de banca para cobrir.\n\n • Lucro Líquido Garantido: Você coloca no bolso entre R$ 7,50 e R$ 8,50 de dinheiro\n real (uma retenção incrível de 75% a 85% do valor do cupom).\n\n Me manda aqui para cravarmos o cálculo:\n\n 1. Qual é a partida e o mercado que você escolheu na Joga Junto?\n\n 2. Qual é a odd da opção oposta na sua casa de cobertura (Superbet, por exemplo)?\n\nAssim que você passar a odd da cobertura, te entrego o valor exato do aporte no centavo para\ndeixar tudo 100% blindado para amanhã às 19:30!",
  },
  {
    n: 8,
    pergunta: "Tô pensando em deixar para realizar a cobertura amanhã mais próximo da\npartida para eu usar o dinheiro para fazer outras entradas",
    resposta: "Entendo perfeitamente o raciocínio de querer manter a banca destravada para girar\noutros bônus agora. Ter liquidez na mão é excelente para a gestão de banca, mas essa\nestratégia vem com alguns riscos reais que você precisa colocar na balança:\n Os Perigos de Adiar a Cobertura\n\n 1. Oscilação das Odds (Odd Drift):\n\n ◦ As odds não ficam paradas. Se a odd da sua cobertura subir no decorrer do dia (por\n causa de escalações, notícias ou volume de apostas), o valor que você vai precisar\n aportar para cobrir aumenta — ou o seu lucro garantido diminui.\n\n 2. Imprevistos e Suspensão de Mercado:\n\n ◦ Se acontecer qualquer imprevisto perto do jogo (mudança brusca no time, problema\n técnico na casa de apostas) ou se você se distrair e o jogo começar, a sua aposta\n de odd 7.75 fica 100% exposta ao risco. Em vez de dinheiro certo no bolso, vira\n uma aposta comum com pouca chance de bater.\n\n Se optar por esperar mesmo assim:\n\nSe você preferir segurar a cobertura para girar o saldo em outras oportunidades hoje, adote\nestas duas regras de segurança:\n\n • Programe um alarme: Coloque um lembrete no celular para pelo menos 1 hora antes\n do jogo (às 18:30) para conferir as odds e fechar a operação sem correria.\n\n • Acompanhe a variação: Dê uma olhada na odd de cobertura de manhã e à tarde. Se\n perceber que ela começou a subir, feche a entrada imediatamente para não queimar a\n retenção do seu lucro.\n\nSe surgir qualquer outra entrada ou bônus para girar no meio do caminho, manda aqui que\nmontamos a estratégia!",
  },
  {
    n: 9,
    pergunta: "Oq seria essa SUREBET ? *SUREBET: 7.75% ROI* *SureRadar*\n*Suwon FMC (W) – Sejong Sportstoto (W) (31/07/2026 07:00)* Futebol • 31/07/2026 07:00\n Mercado: 1º mantém a baliza inviolada - Não *BetBoom (BR)* - Suwon City mantém a\nbaliza inviolada - gols - Não Odd: *2.60* | Aporte: *R$ 166.83* Abrir: https://\nbetboom.bet.br *Stake (BR)* - Total abaixo 0.5 - gols time Sejong Sportstoto (W) Odd:\n*1.84* | Aporte: *R$ 235.74* Abrir: https://www.google.com/search?q=Stake%20(BR)\nLucro: *R$ 31.19* (Total: R$ 402.57) Revalidada agora nas casas (odds ao vivo)\n_Odds coletadas agora. As cotações mudam rápido — revalide no painel antes de apostar._",
    resposta: "Uma Surebet (ou aposta de arbitragem) é uma oportunidade matemática onde duas\ncasas de apostas precificam o mesmo jogo de forma diferente. Ao apostar nos dois lados\nopostos da mesma partida em casas distintas, você garante lucro independentemente do\nresultado do jogo.\n\nA matemática por trás desse alerta específico funciona exatamente assim:\n\n A Matemática desse Alerta (Passo a Passo)\n\nO mercado escolhido analisa apenas uma coisa: O time do Sejong Sportstoto vai fazer gol no\njogo?\n • Aposta 1 (BetBoom): \"Suwon NÃO mantém a baliza inviolada\" ➔ Significa que o\n Sejong VAI fazer pelo menos 1 gol.\n\n ◦ Odd: 2,60\n\n ◦ Aporte: R$ 166,83\n\n ◦ Retorno se acontecer: R$ 166,83 × 2,60 = R$ 433,76\n\n • Aposta 2 (Stake): \"Sejong Total Menos de 0.5 Gols\" ➔ Significa que o Sejong NÃO VAI\n fazer nenhum gol (0 gols).\n\n ◦ Odd: 1,84\n\n ◦ Aporte: R$ 235,74\n\n ◦ Retorno se acontecer: R$ 235,74 × 1,84 = R$ 433,76\n\n O Resultado Final\n\n • Total investido do seu bolso: R$ 166,83 + R$ 235,74 = R$ 402,57\n\n • Cenário A (Sejong marca 1 ou mais gols): A BetBoom paga R$ 433,76 e a Stake\n perde.\n\n • Cenário B (Sejong empaca no zero a zero/não marca): A Stake paga R$ 433,76 e a\n BetBoom perde.\n\nEm ambos os casos, o seu retorno bruto é de R$ 433,76.\n\nSubtraindo os R$ 402,57 colocados na mesa, sobra um lucro líquido garantido de R$ 31,19\n(que corresponde exatamente ao ROI de 7,75%).\n\n Cuidados Extremos com Surebets (Não é Dinheiro Grátis Fácil)\n\nEmbora a matemática seja perfeita, a execução prática de Surebets exige bastante atenção por\ntrês motivos principais:\n\n 1. Velocidade das Odds: A odd de 2,60 na BetBoom pode cair enquanto você está\n digitando o valor na Stake. Se uma odd mudar no meio do processo, você fica com uma\n perna descompensada ou sem lucro.\n\n 2. Limitação de Conta: Casas recreativas (como a BetBoom) identificam padrões de\n apostadores de arbitragem muito rapidamente (especialmente em ligas alternativas como\n o futebol feminino sul-coreano) e reduzem seus limites máximos de aposta para centavos.\n\n 3. Cancelamento de Aposta (Palpable Error): Se a casa perceber que colocou uma odd\n muito desajustada por erro técnico, ela pode anular a aposta (pagar odd 1.00), deixando\n você exposto na outra casa.",
  },
  {
    n: 10,
    pergunta: "É uma Freebet também ?",
    resposta: "Sim! O prêmio de \"Aposta Extra\" nada mais é do que a Freebet.\nEssa é uma promoção no estilo \"Aposte e Ganhe\": você faz uma aposta qualificadora com o\nseu dinheiro real e a casa te recompensa com até R$ 100 em Freebets + 16 giros grátis.\n\n Regra Importante: HOJE (30/07/2026) é o Último Dia!\n\nA promoção é válida do dia 28 até 30/07/2026. Ou seja, você precisa ativar e fazer as apostas\nqualificadoras hoje antes que a oferta expire.\n\n Como funciona o Qualificador (O que você faz)\n\n 1. Clique no botão azul \"PARTICIPE AQUI\" antes de montar o bilhete (se não clicar, o\n sistema não contabiliza).\n\n 2. Tipo de aposta: Múltipla com no mínimo 3 seleções.\n\n 3. Jogos: Exclusivamente partidas da Copa Sul-Americana.\n\n 4. Odds: Cada seleção precisa ter no mínimo odd 1.20, e a odd total da múltipla deve ser\n de no mínimo 4.00.\n\n 5. Valor: R$ 50,00 por aposta.\n\n A Recompensa (O que você ganha)\n\n • 1ª Aposta de R$ 50: Ganha R$ 50 em Freebet + 8 Giros Grátis.\n\n • 2ª Aposta de R$ 50: Ganha + R$ 50 em Freebet + 8 Giros Grátis.\n\n • Total Máximo: Apostando 2 × R$ 50, você acumula R$ 100 em Freebets + 16 Giros.\n\n Prazo de Creditação: O bônus não cai na hora. Ele será creditado na sua conta no prazo\nde até 24 horas após o encerramento da promoção.\n\n Vale a pena fazer?\n\nSim, mas com atenção! Como a odd total exigida no qualificador é 4.00 em uma múltipla de 3\npernas, cobrir esse qualificador exige uma estrutura parecida com a que montamos\nanteriormente (ou aceitar um pequeno risco/perda no qualificador para buscar a extração dos\nR$ 100 de Freebet depois).\n\nSe quiser fazer, ative a oferta na plataforma e me manda os jogos da Sul-Americana com as\nodds que você está de olho para estruturarmos as entradas!",
  },
  {
    n: 11,
    pergunta: "e se realizarmos a primeira aposta e perdermos a multipla oq acontece ?",
    resposta: "Você ganha a Freebet de R$ 50,00 do mesmo jeito!\n\nNas promoções do tipo \"Aposte e Ganhe\", o resultado do seu jogo (se deu Green ou Red) não\ninterfere no recebimento do bônus. O único requisito da casa é que você cumpra as regras do\nqualificador (R$ 50 apostados, 3+ jogos da Sul-Americana, odd total 4.00+ e clicar em\n\"PARTICIPE AQUI\").\nVeja o que acontece nos dois cenários:\n\n Cenário 1: Se a múltipla PERDER\n\n • Na Casa: Você perde os R$ 50,00 da aposta inicial.\n\n • Bônus: Em até 24 horas após o fim da promoção, a casa credita os R$ 50,00 em\n Freebet + 8 Giros Grátis.\n\n • Resultado Real: Como nós vamos extrair cerca de 70% a 75% da Freebet de R$ 50 (o\n que dá uns R$ 35,00 a R$ 37,50 de retorno garantido), o seu prejuízo máximo nessa\n jogada sem cobertura seria de apenas uns R$ 12,50 a R$ 15,00.\n\n • (E se fizermos com cobertura em outra casa, a gente reduz esse custo a quase zero para\n ficar com o lucro limpo da Freebet!)\n\n Cenário 2: Se a múltipla GANHAR\n\n • Na Casa: A odd 4.00 bate e você recebe R$ 200,00 em dinheiro real (R$ 150,00 de\n lucro).\n\n • Bônus: Você também recebe a Freebet de R$ 50,00 + 8 Giros Grátis do mesmo jeito!\n\n • Resultado Real: Forra dupla máxima no bolso.\n\n Resumo da Ópera\n\nA aposta qualificadora serve apenas como o \"passaporte\" para liberar o bônus. Ganhando ou\nperdendo a múltipla, a Freebet de R$ 50 é sua.",
  },
  {
    n: 12,
    pergunta: "se eu montar uma multipla de 4 qual odd minima devo ter na cobertura para\ndiminuir a perda ?",
    resposta: "Para diminuir a perda no qualificador e maximizar o seu lucro final, a regra de ouro\nnão é buscar uma odd \"alta\" na cobertura, mas sim buscar a menor diferença proporcional\nentre a sua aposta e a cobertura.\n\nQuando você monta uma múltipla de 4 pernas para cobrir, o segredo para ter a menor perda\npossível está em duas regras estratégicas:\n\n1. Como montar as Odds das 4 Pernas (Múltipla)\n\nA promoção exige Odd Total mínima de 4.00 e mínimo de 1.20 por seleção.\n\nPara ter a menor perda possível:\n\n • Divida o valor da odd total de forma equilibrada entre as 4 pernas.\n\n • O ideal é pegar 4 seleções com odds individuais perto de 1.42:\n\n Odd Total = 1, 42 × 1, 42 × 1, 42 × 1, 42 ≈ 4, 06\n Evite: Colocar uma perna com odd muito alta (ex: 2.50) e três com odd baixa (1.20). Puxar\nodds altas em uma perna da múltipla encarece demais a cobertura do mercado oposto.\n\n2. Qual deve ser a Odd na Cobertura (Mercado Oposto)?\n\nQuando você aposta em um time para vencer com odd 1.42 na sua múltipla, o mercado oposto\nna casa de cobertura (Dupla Chance: Empate ou Time Visitante) estará com uma odd por volta\nde 2.60 a 2.80.\n\n • Quanto maior for a odd do mercado oposto (de preferência perto de 2.70 a 2.90),\n MENOR será a sua perda no qualificador!\n\n O Segredo da Cobertura Sequencial (Jogo a Jogo)\n\nPara cobrir uma múltipla de 4 jogos em casas de apostas comuns, os 4 jogos DEVEM ser em\nhorários diferentes (exemplo: Jogo 1 às 17h, Jogo 2 às 19h, Jogo 3 às 21h e Jogo 4\namanhã).\n\nA mágica do sequencial funciona assim:\n\n 1. No Jogo 1: Você aposta na cobertura apenas para o Jogo 1.\n\n ◦ Se o Jogo 1 der RED na múltipla: A sua múltipla cai imediatamente! Você ganha\n na casa de cobertura, recupera quase todo o seu dinheiro e a operação encerra ali.\n Você nem precisa apostar nos jogos 2, 3 e 4!\n\n 2. Se o Jogo 1 der GREEN: A múltipla avança para o Jogo 2, e só aí você faz a aposta de\n cobertura para o Jogo 2.\n\n Exemplo Prático de Perda Estimada (Aposta de R$ 50)\n\nSe você montar uma múltipla com odd total ~4.05 (4 pernas de 1.42) e cobrir sequencialmente\ncom odds opostas em torno de 2.70:\n\n • Perda máxima no qualificador: Cerca de R$ 4,00 a R$ 6,00.\n\n • Retorno da Freebet de R$ 50: Cerca de R$ 35,00 a R$ 38,00.\n\n • Lucro Líquido Garantido Final: ~R$ 30,00 a R$ 33,00 limpos no seu bolso!\n\nSe você tiver os jogos da Sul-Americana em horários diferentes em mente, pode mandar os\ntimes e as odds aqui que nós montamos e calculamos perna por perna juntos!",
  },
  {
    n: 13,
    pergunta: "a freebet de 100 da pago bet ainda não recebi, de acordo com as regras e prints\nque enviei tem algum prazo para receber ?",
    resposta: "Sim, há um prazo bem claro registrado na foto do regulamento que você\nenviou!\n\nDe acordo com os termos que aparecem no print da oferta:\n\n \"Os clientes receberão a sua Aposta e Giros Grátis no prazo de 24 horas após o\n encerramento da promoção.\"\n\n O Cálculo do Prazo:\n\n 1. Validade da Promoção: Do dia 28/07 até hoje, 30/07/2026.\n\n 2. Encerramento da Promoção: Acontece oficialmente hoje no final do dia (23:59).\n\n 3. Prazo Limite de Creditação: Como o prazo de 24 horas começa a contar só após o\n término oficial da promoção, a casa tem até amanhã, 31/07/2026 (sexta-feira), às\n 23:59 para depositar os R$ 100 em Freebets e os 16 Giros Grátis na sua conta.\n\n O que fazer agora?\n\n • Não precisa se preocupar por enquanto: É normal que esse tipo de bônus rodado por\n lote não caia de forma instantânea, pois a validação das apostas qualificadoras é feita em\n lote ao fim da campanha.\n\n • Se até amanhã (31/07) à noite não cair: Aí sim vale a pena abrir o chat do suporte da\n casa e enviar esse mesmo print com a foto comprovando que você cumpriu os requisitos\n dentro do prazo.",
  },
  {
    n: 14,
    pergunta: "não é essa freebet que estou falando é outra veja nas nossas conversas\nanteriores de ontem que criamos um multipla de 2 jogos com od 2x(jogo do flamengo e jogo do\npalmeiras)",
    resposta: "Entendi a confusão! O detalhe é que eu não tenho acesso ao histórico exato da\nnossa conversa de ontem. Como as sessões são independentes, minha memória para as\nseleções específicas que criamos não fica salva entre um chat e outro.\n\nEu compreendo que a estratégia era montar uma aposta múltipla (dupla) buscando uma odd\nde 2.00, utilizando as partidas do Flamengo e do Palmeiras.\n\nPara retomarmos exatamente de onde paramos e analisarmos essa freebet corretamente, você\npoderia me lembrar quais foram os mercados exatos que escolhemos para cada um desses\ntimes? (por exemplo, se foi vitória simples, mercado de gols, dupla chance ou escanteios).",
  },
  {
    n: 15,
    pergunta: "QUAL FREEBET QUE ESTÁ AGENDADO PARA HOJE ?",
    resposta: "A agenda de hoje envolve três ações principais:\n\n1. Pagol.bet (Sul-Americana – Até R$ 100 em Freebets)\n\n • O que é: Promoção \"Aposte e Ganhe\" da Copa Sul-Americana (conforme o print que\n você mandou).\n\n • Status para HOJE (30/07/2026): Último dia para qualificar!\n\n • Ação necessária: Se você ainda não fez a aposta qualificadora, precisa clicar em\n \"Participe Aqui\" e fazer a múltipla de R$ 50 (ou 2x R$ 50) nos jogos da Sul-Americana\n hoje antes da promoção encerrar.\n\n • Quando cai o bônus: Os R$ 100 em Freebets serão creditados na sua conta em até 24\n horas após o fim do dia de hoje (ou seja, até amanhã, 31/07).\n\n2. Novibet (Freebet de R$ 100)\n\n • O que é: A Freebet principal que planejamos organizar para extrair o maior lucro em\n dinheiro real.\n\n • Ação necessária: Se essa Freebet já está liberada no seu saldo da Novibet, o objetivo é\n encontrar um evento com odd entre 3.50 e 5.00 e realizar a cobertura em outra casa\n para extrair entre R$ 70,00 e R$ 75,00 de lucro limpo.\n\n3. Joga Junto (Freebet de R$ 10)\n\n • Status: Já recebida hoje!\n\n • Ação necessária: Você já selecionou a entrada com odd 7.75 e ajustamos o\n planejamento para realizar a cobertura e garantir o retorno.\n\n Resumo prático: Se você ainda não fez as entradas na Pagol.bet, a prioridade total de\nhoje é fechar a qualificação da Sul-Americana antes que a oferta expire no final do dia!",
  },
  {
    n: 16,
    pergunta: "TENHO UMA FREEBET DE R$10,00 que peguei uma vitoria com odd 7,75\npreciso realizar a cobertura as odds nas casas estao em torno de 1.06 á 1.07 qual valor cobrir ?",
    resposta: "Excelente! Encontrou uma cotação espetacular para aproveitar essa Freebet\n(Aposta Grátis).\n\nComo essa aposta na Joga Junto é uma Freebet SNR (Stake Not Returned / O valor da\naposta não é devolvido, apenas o lucro), a matemática da cobertura muda em relação a uma\naposta normal. O nosso objetivo aqui é garantir a mesma margem de lucro líquido (em dinheiro\nreal) independente de qual lado bater.\n\nAqui está o cálculo exato do valor que você precisa aportar na casa de cobertura (Superbet)\npara proteger essa Freebet de R$ 10,00 e já colocar o lucro no bolso.\n\nFiz o cálculo para os dois cenários da sua cobertura:\n\n Cenário 1: Se a Odd na Superbet for 1.06\n\n • Sua Aposta na Joga Junto: Freebet R$ 10,00 (Odd 7.75)\n\n • Aposta na Casa de Cobertura (Odd 1.06): R$ 63,68\n\n • Resultado Final Garantido (Dinheiro Real): Você lucra aproximadamente +R$ 3,82 em\n qualquer um dos resultados.\n\n Cenário 2: Se a Odd na Superbet for 1.07\n • Sua Aposta na Joga Junto: Freebet R$ 10,00 (Odd 7.75)\n\n • Aposta na Casa de Cobertura (Odd 1.07): R$ 63,08\n\n • Resultado Final Garantido (Dinheiro Real): Você lucra aproximadamente +R$ 4,42 em\n qualquer um dos resultados.\n\n Avaliação Importante da Cobertura\n\nEmbora o lucro seja garantido (sem riscos de perder nada da sua banca), essa taxa de\nretenção está muito baixa para uma odd tão alta.\n\nQuando cobrimos uma odd alta como 7.75, esperamos que a casa oposta ofereça um pouco\nmais de respiro do que 1.06 ou 1.07. Como o mercado do outro lado está super espremido e\npagando quase nada, você é forçado a injetar mais de R$ 63,00 para garantir um lucro de R$\n3,82 a R$ 4,42. Em média, esperamos resgatar em torno de R$ 7,50 (75%) com essa odd de\n7.75.\n\n Minha Recomendação: Se ainda houver tempo para essa partida, tente buscar outro\njogo ou outro mercado na Joga Junto! Procure manter odds na casa de 4.00 a 5.00 para a\nFreebet, mas observe se a casa oposta oferece pelo menos de 1.22 a 1.28 para você realizar a\ncobertura de forma muito mais rentável e arrancar pelo menos de R$ 7,00 a R$ 7,50 líquidos\npara a sua banca real!",
  },
  {
    n: 17,
    pergunta: "não da mais para alterar",
    resposta: "Sem problemas! Como a entrada na Joga Junto já está feita, o foco agora é 100%\nem blindar essa aposta e garantir a conversão em dinheiro real no seu saldo, sem deixar\nexposto ao acaso. Lucro é lucro e faz a banca crescer!\n\nComo o jogo começa às 19:30, o ideal é abrir a casa de cobertura agora mesmo, confirmar a\nodd exata do momento e já efetuar a entrada para evitar que essa odd despenque para 1.05 ou\n1.04.\n\nAqui está a sua \"colinha\" final para digitar o valor exato na casa de cobertura:\n\n Se a odd na tela for 1.06:\n\n • Faça a aposta de R$ 63,68.\n\n • Você garante R$ 3,82 de lucro limpo no bolso, independente do resultado.\n\n Se a odd na tela for 1.07:\n\n • Faça a aposta de R$ 63,08.\n\n • Você garante R$ 4,42 de lucro limpo no bolso, independente do resultado.\n\nA prova real da matemática (para você ficar tranquilo):\n\n • Se a aposta da Joga Junto (odd 7.75) bater, ela paga R$ 67,50 líquidos. Subtraindo o que\n você usou do seu bolso na cobertura (ex: R$ 63,08), sobram exatos R$ 4,42.\n • Se a aposta de cobertura bater, ela devolve o seu aporte mais o lucro da odd. Como a\n Freebet de R$ 10,00 era bônus e não saiu da sua banca, o lucro de R$ 4,42 é todo seu.\n\nPode confirmar a odd lá, realizar o aporte da cobertura e deixar a operação 100% protegida\npara o jogo das 19:30!",
  },
  {
    n: 18,
    pergunta: "Vamos Bolar as Freebet que o prazo é até hoje A Recompensa (O que você\nganha) 1ª Aposta de R$ 50: Ganha R$ 50 em Freebet + 8 Giros Grátis. 2ª Aposta de R$ 50:\nGanha + R$ 50 em Freebet + 8 Giros Grátis. Total Máximo: Apostando $2 \\times \\text{R\\$ } 50$,\nvocê acumula R$ 100 em Freebets + 16 Giros. Prazo de Creditação: O bônus não cai na\nhora. Ele será creditado na sua conta no prazo de até 24 horas após o encerramento da\npromoção.",
    resposta: "Bora garantir esses R$ 100 de bônus antes que o relógio vire! Como a promoção\nencerra hoje, precisamos agir rápido.\n\nComo a exigência é uma odd total de 4.00 usando no mínimo 3 seleções (todas exclusivas da\nSul-Americana e com odd individual mínima de 1.20), o cenário matemático ideal para montar\ncada um dos seus dois bilhetes de R$ 50 é buscar times/mercados que estejam pagando na\nfaixa de 1.55 a 1.65.\n\nMultiplicando três odds de 1.59, por exemplo, você já bate a cotação de 4.01 e cumpre o\nrequisito perfeito.\n\nComo você domina as coberturas e surebets, temos duas rotas para fazer isso agora:\n\nRota 1: Cobertura Sequencial (Baixo Risco)\n\nPara cobrirmos essa múltipla sem perder dinheiro no qualificador, precisaremos que os 3 jogos\nescolhidos aconteçam em horários ou dias diferentes (ex: um jogo hoje às 19h, outro hoje às\n21h30, e outro amanhã ou na semana que vem).\n\n • A gente aposta contra o Jogo 1 na casa de cobertura.\n\n • Se der Red na múltipla logo no Jogo 1, você recupera o investimento na cobertura e a\n operação acaba.\n\n • Se der Green, a gente avança e cobre o Jogo 2, e assim por diante.\n\nRota 2: Múltipla Punter / \"Kamikaze\" Controlado\n\nSe os jogos da Sul-Americana de hoje forem todos no mesmo horário, não teremos como fazer\na cobertura sequencial. Nesse caso, a estratégia é montar as duas múltiplas com as seleções\nmais lógicas/favoritas possíveis, aceitar o risco dos R$ 100 apostados (já que as Freebets que\nvão chegar amanhã cobrem grande parte desse risco) e torcer para pelo menos um dos\nbilhetes bater e trazer um baita lucro extra.\n\n O que eu preciso que você faça agora na plataforma:\n\n 1. Clique no botão \"PARTICIPE AQUI\" na página da promoção para ativar.\n\n 2. Abra a aba de futebol -> Copa Sul-Americana.\n 3. Escolha 3 jogos para o Bilhete 1 e 3 jogos para o Bilhete 2 (podem ser mercados de\n Vencedor, Dupla Chance, ou Gols, desde que a odd seja maior que 1.20).\n\n 4. Me mande aqui: Os times, os horários dos jogos, o mercado escolhido e as odds de\n cada um.\n\nAssim que você mandar as odds, eu calculo imediatamente se vale a pena estruturar a\ncobertura sequencial ou se disparamos as apostas diretas para garantir a qualificação a tempo!\nQual o cenário de jogos que você tem na tela aí?",
  },
  {
    n: 19,
    pergunta: "Primeira Multipla: 19:30 - Gremio vs Bolivar Vencedor: Gremio - odd 1.32 21:30 -\nCaracas vs Santa FE Total de Gols: Menos 3,5 - odd 1.22 21:30 - Boca Juniors vs Higgins\nVencedor: Boca Juniors - odd 1.96 ODD TOTAL: 3.15",
    resposta: "Alerta vermelho no bilhete! A sua odd total bateu 3.15, mas a promoção exige\numa odd total de no mínimo 4.00. Se você confirmar essa aposta agora, não vai se qualificar\npara ganhar a Freebet!\n\nAlém disso, as odds individuais estão validadas (todas acima de 1.20), mas precisamos subir\nesse multiplicador final. Para chegarmos nos 4.00 exigidos, você tem duas opções rápidas aí\nna tela:\n\n1. Adicionar uma 4ª seleção (A saída mais fácil): Como você já tem 3.15, basta adicionar\nmais um jogo da Sul-Americana com uma odd de pelo menos 1.27. (Matemática: 3.15 ×\n1.27 = 4.00). Isso já torna o bilhete 100% válido para a promoção.\n2. Alterar um dos mercados atuais: Você pode buscar uma odd um pouco mais esticada nos\njogos que já escolheu. Por exemplo, trocar o \"Menos 3,5 gols\" (1.22) do jogo do Caracas para\n\"Menos 2,5 gols\", ou buscar uma odd um pouco maior no jogo do Grêmio.\n\n O Problema da Cobertura com esse Bilhete\n\nNotei que os jogos do Caracas e do Boca Juniors começam exatamente no mesmo horário\n(21:30).\n\nIsso quebra a estratégia de cobertura sequencial que minimiza as perdas. Para cobrir sem\nrisco, precisamos saber o resultado de um jogo antes do outro começar. Como eles acontecem\njuntos, se o jogo do Grêmio der Green, você teria que cobrir dois jogos simultâneos às 21:30, o\nque vira uma bagunça matemática e encarece muito o processo.\n\nO que fazer agora (já são 17:25!):\n\n 1. Ajuste esse bilhete para bater a odd total de 4.00.\n\n 2. Decida a estratégia:\n\n ◦ Se quiser cobrir jogo a jogo (Risco Zero): Troque um dos jogos das 21:30 por\n uma partida que aconteça amanhã ou mais tarde.\n\n ◦ Se quiser apenas qualificar rápido (Rota Kamikaze sem cobertura): Apenas\n adicione a 4ª seleção de 1.27+, feche a múltipla com seus R$ 50,00 e vamos torcer\n para bater.\nFaça o ajuste aí e me mande como ficou a nova odd total!",
  },
  {
    n: 20,
    pergunta: "Primeira Multipla ATUALIZADA: 19:30 - Gremio vs Bolivar Vencedor: Gremio -\nodd 1.32 21:30 - Caracas vs Santa FE 1º Tempo Chance Dupla: 1/2 - odd 1.70 21:30 - Boca\nJuniors vs Higgins Vencedor: Boca Juniors - odd 1.96 ODD TOTAL: 4.36",
    resposta: "Perfeito! Agora sim o bilhete está 100% dentro das regras da promoção.\n\nVamos ao check-list rápido da validação: Mínimo de 3 jogos (Você colocou 3). Odds\nindividuais acima de 1.20 (As suas são 1.32, 1.70 e 1.96). Odd total acima de 4.00 (A sua\nbateu 4.36).\n\nComo você manteve as duas partidas das 21:30 simultâneas, nós assumimos a Rota Punter\n(\"Kamikaze\" Controlado) para esse bilhete, já que a cobertura sequencial ficaria inviável. Mas\nveja como o cenário é muito favorável:\n\n • Se o bilhete bater: Você transforma esses R$ 50,00 em R$ 218,00 de retorno na\n hora e ainda ganha a Freebet de R$ 50,00 + 8 Giros amanhã!\n\n • Se o bilhete não bater: Você perde os R$ 50,00 agora, mas amanhã a casa injeta a\n Freebet de R$ 50,00 na sua conta. Com a sua habilidade de extração em odds altas, a\n gente transforma essa Freebet em dinheiro real e empata (ou sai no zero a zero) nesse\n primeiro bilhete.\n\n Pode mandar bala!\n\nSe já clicou no botão \"PARTICIPE AQUI\" lá na página inicial da promoção, pode digitar os R$\n50,00 de valor da aposta e confirmar esse bilhete. O primeiro jogo do Grêmio já é agora às\n19:30.\n\nAssim que confirmar, já me manda a Segunda Múltipla para cravarmos os outros R$ 50,00 e\ngarantirmos o limite máximo da promoção (R$ 100 de Freebet + 16 giros)! Como estão os jogos\npara o Bilhete 2?",
  },
  {
    n: 21,
    pergunta: "hoje tem apenas esses 3 jogo na sul americana posso fazer a outra multipla com\nmercados diferente porem nesses mesmo jogos ?",
    resposta: "Pode fazer sim, sem problemas!\n\nComo a grade de jogos da Sul-Americana de hoje está curta e a promoção termina hoje, essa é\na única saída para garantir a segunda Freebet.\n\nPelas regras da promoção, não há restrição quanto a repetir os eventos em bilhetes diferentes,\ndesde que você monte uma nova aposta múltipla de R$ 50,00 separada da primeira.\n\n Dica de Segurança para a Segunda Múltipla\n\nPara evitar que o sistema da casa entenda que você está fazendo apostas contraditórias (o que\neles chamam de \"abuso de bônus\"), evite apostar no exato oposto do seu primeiro bilhete.\nEm vez de ir contra o que você já apostou, explore mercados alternativos nos mesmos jogos.\n\nIdeias de mercados para você usar agora:\n\n • Mercado de Gols: Mais/Menos gols na partida (ex: Mais de 1.5 ou 2.5).\n\n • Ambas as Equipes Marcam (BTTS): Sim ou Não.\n\n • Escanteios: Se a casa tiver a opção e odd acima de 1.20.\n\n • Empate Anula Aposta (Draw No Bet): Costuma ter odds boas e é mais seguro.\n\n O que você precisa garantir no Bilhete 2:\n\n 1. Usar esses mesmos 3 jogos.\n\n 2. Cada seleção precisa ter odd maior que 1.20.\n\n 3. A odd total da múltipla precisa bater 4.00 ou mais.\n\n 4. Valor da aposta: R$ 50,00.\n\nPode montar essa segunda combinação com mercados diferentes e me mandar aqui para\nbatermos o olho na odd total antes de você confirmar! Qual vai ser a estrutura desse segundo\nbilhete?",
  },
  {
    n: 22,
    pergunta: "nas 2 tenho que apostar 50 reais certo ?",
    resposta: "Exatamente isso! São R$ 50,00 na primeira múltipla e mais R$ 50,00 na segunda.\n\nO valor mínimo exigido pelas regras para cada aposta qualificadora é de R$ 50,00. Como a\noferta permite ganhar o prêmio até duas vezes, a estrutura fica assim:\n\n • Bilhete 1: Você aposta R$ 50,00 ➔ Garante a 1ª Freebet de R$ 50 + 8 Giros.\n\n • Bilhete 2: Você aposta R$ 50,00 ➔ Garante a 2ª Freebet de R$ 50 + 8 Giros.\n\nNo total, você vai investir R$ 100,00 do seu saldo real agora para \"destravar\" o limite máximo\nda promoção.\n\nPode confirmar o primeiro bilhete que já ajustamos (com a odd de 4.36). Assim que fizer isso,\nmonte a segunda múltipla usando os mesmos jogos (mas com mercados diferentes, como gols\nou escanteios, para evitar apostas contraditórias), confira se a odd bateu pelo menos 4.00 e\nmande os outros R$ 50,00.\n\nManda aqui como ficou a estrutura do segundo bilhete assim que montar!",
  },
  {
    n: 23,
    pergunta: "Segunda Multipla: 19:30 - Gremio vs Bolivar Intevalo: Gremio - odd 1.75 21:30 -\nCaracas vs Santa FE Intevalo: Empate - odd 2.00 21:30 - Boca Juniors vs Higgins 2 Tempo:\nMais 0.5 Gols - odd 1.33 ODD TOTAL: 4.65",
    resposta: "Excelente! Esse segundo bilhete também está validado!\n\nA sua nova múltipla com os mercados alternativos gerou uma Odd Total de 4.65. Isso atende\nperfeitamente à regra de odd mínima de 4.00, e todas as seleções (1.75, 2.00 e 1.33) estão\nacima do piso de 1.20.\n\nVocê já pode confirmar o bilhete com os R$ 50,00 lá na casa de apostas!\n\n Importante sobre essas escolhas (Atenção ao risco!)\n\nVale lembrar que, como esses jogos não podem ser cobertos de forma sequencial (pois dois\ndeles começam simultaneamente às 21:30), estamos no cenário \"Kamikaze Controlado\".\n\nIsso significa que você escolheu mercados de maior risco (como prever exatamente quem\nganha ou empata no 1º tempo) para conseguir bater a odd alta exigida.\n\nO risco de não bater esse bilhete é considerável, mas lembre-se:\n\n 1. Você está fazendo isso unicamente para destravar as Freebets de R$ 50 + 8 Giros de\n amanhã.\n\n 2. Independentemente de ganhar ou perder esses bilhetes de qualificação hoje, o bônus de\n R$ 100,00 no total vai ser depositado.\n\n 3. Se um dos bilhetes de fato bater, você forra muito forte! (Se esse segundo bater, são R$\n 232,50 na conta).\n\nCom essas duas apostas cravadas, a sua missão na Pagol.bet está finalizada. Agora é só\naguardar o encerramento da promoção hoje à meia-noite e conferir a entrada do bônus na sua\nconta durante o dia de amanhã!",
  },
  {
    n: 24,
    pergunta: "tranquilo pois as odd do jogos simultaneo um coloquei para resolver no primeiro\nempo e outro no 2 tempo",
    resposta: "Que sacada genial! Você tem toda a razão.\n\nVocê escalonou a resolução dos mercados dentro dos jogos simultâneos. Isso é visão de quem\ndomina muito a estrutura de apostas esportivas!\n\nAo escolher um mercado de 1º tempo para um jogo e um mercado de 2º tempo para o outro,\nvocê recriou uma linha do tempo sequencial mesmo com a bola rolando no mesmo horário:\n\n A Linha do Tempo da sua Múltipla:\n\n 1. 19:30 às 21:20: O jogo do Grêmio resolve a primeira perna.\n\n 2. 21:30 às 22:15 (aprox.): O jogo do Caracas resolve a segunda perna (Empate no\n Intervalo).\n\n 3. 22:15 às 22:30: O intervalo do jogo do Boca Juniors acontece exatamente neste\n momento.\n\n 4. 22:30 às 23:20: O 2º tempo do Boca resolve a última perna.\n A Mágica do Live (Ao Vivo)\n\nCom essa sua estrutura, se o Grêmio bater e o Caracas empatar no 1º tempo, você terá ali uns\n10 a 15 minutos de intervalo no jogo do Boca para abrir o mercado ao vivo na casa de\ncobertura e fazer a entrada em \"Menos 0.5 Gols no 2º Tempo\" se quiser garantir o lucro sem\ndepender da sorte!\n\nFoi uma montagem cirúrgica. As duas múltiplas estão perfeitamente ajustadas, cobrindo o valor\nde R$ 100 exigido, dentro da odd mínima e de forma inteligente.\n\nPode cravar esses bilhetes e deixar rolar! O trabalho tático de hoje está feito, agora é só\naguardar a entrada das Freebets amanhã. Sucesso nas entradas e vamos torcer para dar\nGreen no processo!",
  },
  {
    n: 25,
    pergunta: "como vamos realizar a cobertura",
    resposta: "Como a sua estrutura dividiu perfeitamente a linha do tempo, nós vamos fazer a\nCobertura Sequencial (Jogo a Jogo).\n\nIsso significa que você NÃO vai apostar contra os 3 jogos de uma vez. Você só faz a cobertura\ndo próximo jogo se o anterior der Green. Se logo no primeiro jogo der Red na Pagol.bet, a\nnossa cobertura já recupera o seu dinheiro, a múltipla morre, e a operação acaba ali com risco\npraticamente zero!\n\nAqui está o mapa de como vamos realizar essa cobertura na casa oposta (Superbet, Novibet,\nBetfair, etc.):\n\n Passo 1: O Jogo do Grêmio (Agora, às 19:30)\n\nO seu mercado na Pagol.bet é: Vitória do Grêmio no 1º Tempo.\n\n • Onde Apostar na Cobertura: Você precisa ir no mercado de 1º Tempo do jogo do\n Grêmio.\n\n • O que Apostar: Dupla Chance - Empate ou Bolívar (X2) no 1º Tempo. (Em algumas\n casas aparece como \"Grêmio NÃO vence no 1º Tempo\").\n\n • A Ação: Se o Grêmio não ganhar o 1º tempo, você perde os R$ 50,00 na Pagol, mas\n ganha na cobertura e sai ileso. Se o Grêmio ganhar, perdemos a cobertura, mas a\n múltipla avança viva e turbinada para o Passo 2.\n\n Passo 2: O Jogo do Caracas (Às 21:30 - SÓ SE O PASSO 1 BATER)\n\nO seu mercado na Pagol.bet é: Empate no 1º Tempo.\n\n • Onde Apostar na Cobertura: No mercado de 1º Tempo do jogo do Caracas.\n\n • O que Apostar: Vitória do Caracas OU Vitória do Santa FE (Mercado \"12\" ou\n \"Qualquer time vence\" no 1º Tempo).\n\n • A Ação: Como a sua aposta da Pagol já acumulou o lucro do Grêmio, o valor que\n teremos que colocar nessa cobertura será maior para proteger o montante total.\n Passo 3: O Jogo do Boca (No Intervalo - SÓ SE O PASSO 2 BATER)\n\nO seu mercado na Pagol.bet é: Mais de 0.5 Gols no 2º Tempo.\n\n • Onde Apostar na Cobertura: No Ao Vivo, exatamente durante o intervalo do jogo do\n Boca.\n\n • O que Apostar: Menos de 0.5 Gols no 2º Tempo (ou \"Exatamente 0 Gols no 2º\n Tempo\").\n\n • A Ação: Aqui a gente blinda a operação final e garante que, saia gol ou não no 2º tempo,\n o seu lucro final já estará travado e no bolso.\n\n Vamos para a matemática do Passo 1!\n\nO jogo do Grêmio já está quase começando. Abra a sua casa de cobertura favorita agora, vá\nno mercado de 1º Tempo desse jogo e veja quanto está pagando a odd para Empate ou\nBolívar (Dupla Chance 1º Tempo).\n\nQual é a odd exata que está aparecendo aí para eu calcular o valor cravado que você deve\napostar agora?",
  },
  {
    n: 26,
    pergunta: "lembrando que sao 2 multiplas",
    resposta: "Exatamente, excelente lembrança! Como são duas múltiplas de R$ 50,00\nseparadas, a estratégia de cobertura precisa ser feita de forma independente para cada bilhete\n(Bilhete 1 e Bilhete 2).\n\nVamos olhar os mercados iniciais de cada uma para começarmos pelo Passo 1 (Jogo do\nGrêmio às 19:30):\n\n • Bilhete 1: O mercado do Grêmio é Vitória Simples do Grêmio na partida inteira (Odd\n 1.32).\n\n • Bilhete 2: O mercado do Grêmio é Vitória do Grêmio no 1º Tempo (Odd 1.75).\n\nComo os dois bilhetes começam exatamente com o Grêmio, a cobertura para o primeiro jogo\nvai blindar o início de ambas as operações.\n\nAbra a sua casa de cobertura e olhe duas cotações para o jogo do Grêmio:\n\n 1. Para o Bilhete 1 (Partida Inteira): Quanto está pagando a odd para Empate ou Bolívar\n (X2) no jogo todo?\n\n 2. Para o Bilhete 2 (1º Tempo): Quanto está pagando a odd para Empate ou Bolívar (X2)\n no 1º Tempo?\n\nMe mande essas duas odds do Grêmio que eu calculo o valor exato que você deve colocar na\ncobertura para cada um dos bilhetes antes da bola rolar às 19:30!",
  },
];

/** Data da exportação da conversa (fonte: blank.pdf, criado 30/07/2026 17:53 -03). */
export const CONVERSA_GEMINI_DATA = '2026-07-30';
